os: linux
language: python
python:
  - "3.8"

services:
  - docker

install:
  - pip3 install --upgrade --user awscli

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - bash .travis/setup.sh

script:
  - docker-compose -f docker-compose.test.yml up

after_success:
  - bash .travis/pull.sh
  - bash .travis/build.sh

deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      branch: master
