os: linux
language: python

services:
  - docker

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

install:

before_script:
  - chmod a+x .travis/*.sh
  - export PATH=$HOME/.local/bin:$PATH
  - bash .travis/setup.sh

script:
  - docker-compose -f docker-compose.test.yml up

after_success:
  - bash .travis/pull.sh
  - bash .travis/build.sh

deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      branch: master
