os: linux
language: python
virtualenv:
  system_site_packages: true
python:
  - "3.8"

services:
  - docker

install:
  - pip install --upgrade --user awscli

before_script:
  - export PATH=/usr/bin:$PATH
  - bash .travis/setup.sh

script:
  - docker-compose -f docker-compose.test.yml up

after_success:
  - bash .travis/pull.sh
  - bash .travis/build.sh

deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      branch: master
